### PR TITLE
[TSO-18] create prototype player character

### PR DESCRIPTION
**Pull request by a-lemmon777**

### CODE REVIEW

**Comment by songyang-dev** [comment]
Change the script name to `PlayerController.cs`

**Review by songyang-dev — COMMENTED** [review]
I haven't looked at the scene yet. For now, you should change the name of the script to PlayerController. The input system you are using is the legacy one, which means it cannot be used in tandem with the new one.

**Review by songyang-dev — CHANGES_REQUESTED** [review]
The scene is fine. The requested changes are the same as the previous comments.

**Comment by a-lemmon777** [comment]
Renamed the file! I think I'd like to try out using the new input system, but I'd like to do it as a different task and branch.

**Review by songyang-dev — APPROVED** [review]

**Pull request merged**
